volumes:
  postgres_db_data:

services:
  db:
    ports:
      - "5432:5432"
    image: postgres:16
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pp
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pp
