# Generated by Django 3.1.2 on 2020-10-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('link', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='media')),
            ],
        ),
    ]
