# Generated by Django 3.1.2 on 2020-10-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201024_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='/media/blog/white_image.jpg', null=True, upload_to='blog'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='image',
            field=models.ImageField(blank=True, default='white_image.jpg', upload_to='media'),
        ),
    ]
