# Generated by Django 3.1.2 on 2020-10-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201024_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='/blog/white_image.jpg', null=True, upload_to='blog'),
        ),
    ]
