# Generated by Django 3.1.2 on 2020-10-24 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201024_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='resumo',
            field=models.CharField(blank=True, default='Clique para acessar', max_length=100, null=True),
        ),
    ]
